"""initial schema

Revision ID: 4f96a3e996f2
Revises: 
Create Date: 2026-07-10 04:32:52.150187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f96a3e996f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.Enum('OIL_GAS', 'CONSTRUCTION', 'MANUFACTURING', 'MINING', 'UTILITIES', 'CHEMICALS', 'AGRICULTURE', 'LOGISTICS', 'EVENTS', 'OTHER', name='customer_industry_enum'), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('onboarded_date', sa.Date(), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=False),
    sa.Column('lifetime_value', sa.Float(), nullable=True),
    sa.Column('profitability_score', sa.Float(), nullable=True),
    sa.Column('late_payment_risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='payment_risk_tier_enum'), nullable=True),
    sa.Column('late_payment_probability', sa.Float(), nullable=True),
    sa.Column('recommended_discount_pct', sa.Float(), nullable=True),
    sa.Column('preferred_equipment_type', sa.String(length=64), nullable=True),
    sa.Column('total_rentals', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_index(op.f('ix_customer_company_name'), 'customer', ['company_name'], unique=False)
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_index(op.f('ix_customer_industry'), 'customer', ['industry'], unique=False)
    op.create_index(op.f('ix_customer_is_deleted'), 'customer', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_customer_late_payment_risk'), 'customer', ['late_payment_risk'], unique=False)
    op.create_index(op.f('ix_customer_lifetime_value'), 'customer', ['lifetime_value'], unique=False)
    op.create_index(op.f('ix_customer_region'), 'customer', ['region'], unique=False)
    op.create_table('equipment',
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('asset_tag', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('equipment_type', sa.Enum('COMPRESSOR', 'GENERATOR', 'ANALYZER', 'PUMP', 'EXCAVATOR', 'CRANE', 'FORKLIFT', 'WELDING_MACHINE', 'DRILLING_RIG', 'HVAC_UNIT', name='equipment_type_enum'), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=False),
    sa.Column('model_number', sa.String(length=120), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Float(), nullable=True),
    sa.Column('air_temperature_k', sa.Float(), nullable=True),
    sa.Column('process_temperature_k', sa.Float(), nullable=True),
    sa.Column('rotational_speed_rpm', sa.Float(), nullable=True),
    sa.Column('torque_nm', sa.Float(), nullable=True),
    sa.Column('tool_wear_min', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', name='equipment_status_enum'), nullable=False),
    sa.Column('availability', sa.Enum('AVAILABLE', 'RENTED', 'IN_MAINTENANCE', 'RETIRED', 'IN_TRANSIT', name='rental_availability_enum'), nullable=False),
    sa.Column('current_region', sa.String(length=120), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('base_daily_rate', sa.Float(), nullable=False),
    sa.Column('total_operating_hours', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment'))
    )
    op.create_index(op.f('ix_equipment_asset_tag'), 'equipment', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_equipment_availability'), 'equipment', ['availability'], unique=False)
    op.create_index(op.f('ix_equipment_current_region'), 'equipment', ['current_region'], unique=False)
    op.create_index(op.f('ix_equipment_equipment_type'), 'equipment', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_equipment_health_score'), 'equipment', ['health_score'], unique=False)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_is_deleted'), 'equipment', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_equipment_machine_id'), 'equipment', ['machine_id'], unique=True)
    op.create_index(op.f('ix_equipment_status'), 'equipment', ['status'], unique=False)
    op.create_table('forecast',
    sa.Column('metric', sa.Enum('DEMAND', 'REVENUE', 'PROFIT', 'UTILIZATION', name='forecast_metric_enum'), nullable=False),
    sa.Column('granularity', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', name='forecast_granularity_enum'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('equipment_type', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=True),
    sa.Column('confidence_upper', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast'))
    )
    op.create_index(op.f('ix_forecast_equipment_type'), 'forecast', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_forecast_granularity'), 'forecast', ['granularity'], unique=False)
    op.create_index(op.f('ix_forecast_id'), 'forecast', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_metric'), 'forecast', ['metric'], unique=False)
    op.create_index(op.f('ix_forecast_period_start'), 'forecast', ['period_start'], unique=False)
    op.create_index(op.f('ix_forecast_region'), 'forecast', ['region'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATIONS_MANAGER', 'ANALYST', 'FINANCE', 'FIELD_TECHNICIAN', 'VIEWER', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('alert',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_type', sa.Enum('FAILURE_RISK', 'MAINTENANCE_DUE', 'OVERDUE_RETURN', 'LATE_PAYMENT', 'LOW_INVENTORY', 'PRICE_ANOMALY', 'HEALTH_DEGRADATION', name='alert_type_enum'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['user.id'], name=op.f('fk_alert_acknowledged_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_alert_customer_id_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_alert_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert'))
    )
    op.create_index(op.f('ix_alert_alert_type'), 'alert', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_created_at'), 'alert', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_customer_id'), 'alert', ['customer_id'], unique=False)
    op.create_index(op.f('ix_alert_equipment_id'), 'alert', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_alert_id'), 'alert', ['id'], unique=False)
    op.create_index(op.f('ix_alert_is_acknowledged'), 'alert', ['is_acknowledged'], unique=False)
    op.create_index(op.f('ix_alert_is_resolved'), 'alert', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alert_severity'), 'alert', ['severity'], unique=False)
    op.create_table('audit_log',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=120), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_log_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('decision_recommendation',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('PRICING', 'MAINTENANCE', 'INVENTORY_RELOCATION', 'FLEET_REPLACEMENT', 'CUSTOMER_RETENTION', 'RISK_MITIGATION', name='recommendation_category_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'IMPLEMENTED', 'EXPIRED', name='recommendation_status_enum'), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detailed_reasoning', sa.Text(), nullable=False),
    sa.Column('contributing_prediction_ids', sa.Text(), nullable=False),
    sa.Column('estimated_impact_value', sa.Float(), nullable=True),
    sa.Column('estimated_impact_metric', sa.String(length=64), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_decision_recommendation_customer_id_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_decision_recommendation_equipment_id_equipment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_decision_recommendation_reviewed_by_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_recommendation'))
    )
    op.create_index(op.f('ix_decision_recommendation_category'), 'decision_recommendation', ['category'], unique=False)
    op.create_index(op.f('ix_decision_recommendation_created_at'), 'decision_recommendation', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_recommendation_customer_id'), 'decision_recommendation', ['customer_id'], unique=False)
    op.create_index(op.f('ix_decision_recommendation_equipment_id'), 'decision_recommendation', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_decision_recommendation_id'), 'decision_recommendation', ['id'], unique=False)
    op.create_index(op.f('ix_decision_recommendation_priority_score'), 'decision_recommendation', ['priority_score'], unique=False)
    op.create_index(op.f('ix_decision_recommendation_status'), 'decision_recommendation', ['status'], unique=False)
    op.create_table('equipment_health_snapshot',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'WARNING', 'CRITICAL', name='equipment_status_enum'), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=True),
    sa.Column('remaining_useful_life_days', sa.Float(), nullable=True),
    sa.Column('rul_confidence_lower', sa.Float(), nullable=True),
    sa.Column('rul_confidence_upper', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_health_snapshot_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_health_snapshot'))
    )
    op.create_index(op.f('ix_equipment_health_snapshot_equipment_id'), 'equipment_health_snapshot', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_equipment_health_snapshot_id'), 'equipment_health_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_health_snapshot_recorded_at'), 'equipment_health_snapshot', ['recorded_at'], unique=False)
    op.create_table('maintenance_record',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'PREDICTIVE', 'CORRECTIVE', 'EMERGENCY', 'INSPECTION', name='maintenance_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='maintenance_status_enum'), nullable=False),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('ai_estimated_cost', sa.Float(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('technician_notes', sa.Text(), nullable=True),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_maintenance_record_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_record'))
    )
    op.create_index(op.f('ix_maintenance_record_equipment_id'), 'maintenance_record', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_id'), 'maintenance_record', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_maintenance_type'), 'maintenance_record', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenance_record_status'), 'maintenance_record', ['status'], unique=False)
    op.create_table('prediction',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_type', sa.Enum('PRICE_PREDICTION', 'FAILURE_PREDICTION', 'REMAINING_USEFUL_LIFE', 'HEALTH_SCORE', 'MAINTENANCE_RECOMMENDATION', 'DEMAND_FORECAST', 'REVENUE_FORECAST', 'CUSTOMER_LTV', 'LATE_PAYMENT_RISK', 'INVENTORY_RECOMMENDATION', 'AI_DECISION', name='prediction_type_enum'), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('output_value', sa.Float(), nullable=True),
    sa.Column('output_label', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('shap_values_json', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_prediction_customer_id_customer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_prediction_equipment_id_equipment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction'))
    )
    op.create_index(op.f('ix_prediction_created_at'), 'prediction', ['created_at'], unique=False)
    op.create_index(op.f('ix_prediction_customer_id'), 'prediction', ['customer_id'], unique=False)
    op.create_index(op.f('ix_prediction_equipment_id'), 'prediction', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_prediction_id'), 'prediction', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_model_name'), 'prediction', ['model_name'], unique=False)
    op.create_index(op.f('ix_prediction_prediction_type'), 'prediction', ['prediction_type'], unique=False)
    op.create_table('refresh_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_refresh_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token'))
    )
    op.create_index(op.f('ix_refresh_token_id'), 'refresh_token', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True)
    op.create_table('rental',
    sa.Column('rental_number', sa.String(length=32), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUOTED', 'CONFIRMED', 'ACTIVE', 'RETURNED', 'OVERDUE', 'CANCELLED', name='rental_status_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date_planned', sa.Date(), nullable=False),
    sa.Column('end_date_actual', sa.Date(), nullable=True),
    sa.Column('duration_days_planned', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=True),
    sa.Column('delivery_location', sa.String(length=255), nullable=True),
    sa.Column('market_competitor_price', sa.Float(), nullable=True),
    sa.Column('ai_suggested_price', sa.Float(), nullable=True),
    sa.Column('ai_price_confidence', sa.Float(), nullable=True),
    sa.Column('quoted_daily_rate', sa.Float(), nullable=False),
    sa.Column('final_daily_rate', sa.Float(), nullable=True),
    sa.Column('discount_applied_pct', sa.Float(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('payment_received_date', sa.Date(), nullable=True),
    sa.Column('is_late_payment', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_rental_customer_id_customer'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_rental_equipment_id_equipment'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental'))
    )
    op.create_index(op.f('ix_rental_customer_id'), 'rental', ['customer_id'], unique=False)
    op.create_index(op.f('ix_rental_equipment_id'), 'rental', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_rental_id'), 'rental', ['id'], unique=False)
    op.create_index(op.f('ix_rental_region'), 'rental', ['region'], unique=False)
    op.create_index(op.f('ix_rental_rental_number'), 'rental', ['rental_number'], unique=True)
    op.create_index(op.f('ix_rental_start_date'), 'rental', ['start_date'], unique=False)
    op.create_index(op.f('ix_rental_status'), 'rental', ['status'], unique=False)
    op.create_table('notification',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', name='notification_channel_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_successfully', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], name=op.f('fk_notification_alert_id_alert'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_is_read'), 'notification', ['is_read'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_is_read'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_rental_status'), table_name='rental')
    op.drop_index(op.f('ix_rental_start_date'), table_name='rental')
    op.drop_index(op.f('ix_rental_rental_number'), table_name='rental')
    op.drop_index(op.f('ix_rental_region'), table_name='rental')
    op.drop_index(op.f('ix_rental_id'), table_name='rental')
    op.drop_index(op.f('ix_rental_equipment_id'), table_name='rental')
    op.drop_index(op.f('ix_rental_customer_id'), table_name='rental')
    op.drop_table('rental')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_prediction_prediction_type'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_model_name'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_equipment_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_customer_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_created_at'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_maintenance_record_status'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_maintenance_type'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_id'), table_name='maintenance_record')
    op.drop_index(op.f('ix_maintenance_record_equipment_id'), table_name='maintenance_record')
    op.drop_table('maintenance_record')
    op.drop_index(op.f('ix_equipment_health_snapshot_recorded_at'), table_name='equipment_health_snapshot')
    op.drop_index(op.f('ix_equipment_health_snapshot_id'), table_name='equipment_health_snapshot')
    op.drop_index(op.f('ix_equipment_health_snapshot_equipment_id'), table_name='equipment_health_snapshot')
    op.drop_table('equipment_health_snapshot')
    op.drop_index(op.f('ix_decision_recommendation_status'), table_name='decision_recommendation')
    op.drop_index(op.f('ix_decision_recommendation_priority_score'), table_name='decision_recommendation')
    op.drop_index(op.f('ix_decision_recommendation_id'), table_name='decision_recommendation')
    op.drop_index(op.f('ix_decision_recommendation_equipment_id'), table_name='decision_recommendation')
    op.drop_index(op.f('ix_decision_recommendation_customer_id'), table_name='decision_recommendation')
    op.drop_index(op.f('ix_decision_recommendation_created_at'), table_name='decision_recommendation')
    op.drop_index(op.f('ix_decision_recommendation_category'), table_name='decision_recommendation')
    op.drop_table('decision_recommendation')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alert_severity'), table_name='alert')
    op.drop_index(op.f('ix_alert_is_resolved'), table_name='alert')
    op.drop_index(op.f('ix_alert_is_acknowledged'), table_name='alert')
    op.drop_index(op.f('ix_alert_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_equipment_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_customer_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_created_at'), table_name='alert')
    op.drop_index(op.f('ix_alert_alert_type'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_forecast_region'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_period_start'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_metric'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_id'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_granularity'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_equipment_type'), table_name='forecast')
    op.drop_table('forecast')
    op.drop_index(op.f('ix_equipment_status'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_machine_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_is_deleted'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_health_score'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_type'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_current_region'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_availability'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_asset_tag'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_customer_region'), table_name='customer')
    op.drop_index(op.f('ix_customer_lifetime_value'), table_name='customer')
    op.drop_index(op.f('ix_customer_late_payment_risk'), table_name='customer')
    op.drop_index(op.f('ix_customer_is_deleted'), table_name='customer')
    op.drop_index(op.f('ix_customer_industry'), table_name='customer')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_company_name'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
